### ISSUE TITLE
Templates anpassen für das anzeigen von Bildern in jeder Datei.

### ISSUE THREAD

**Issue by JuliusFaeustel** [htwdd-se/Projektstruktur_OpenUP-Templates#2]
Um Bilder sowohl in dem Bericht als auch in den Vorlagen an sich anzuzeigen habe ich folgenden Workaround gefunden.
ifndef::main-file[]
:imagesdir: bilder
endif::main-file[]
ifdef::main-file[]
:imagesdir: Tests/bilder
endif::main-file[]

Dann noch im Bericht:
:main-file: true

So kann auch wenn die Dateien in verschiedenen Ordnern liegen immer die Bilder von Asciidoc gerendert werden.

**Comment by tigion** [comment]
Danke noch einmal für den Hinweis @JuliusFaeustel. Eine Anpassung ist mit Commit f14291e939d302f29a438af186767f69fc53d288 erfolgt.
